// AUTO-GENERATED by scripts/gen-nav.js — do not edit by hand.
// Run `node scripts/gen-nav.js` (or `./build.sh`) to regenerate.
const navigationData = [
    {
        name: "Introduction",
        slug: "README",
        standalone: true,
    },
    {
        name: "P2P Chat",
        slug: "p2p-chat",
        standalone: true,
    },
    {
        name: "ReactJS",
        slug: "reactjs",
        standalone: true,
    },
    {
        name: "Cognitive Skills",
        slug: "cognitive-skills",
        standalone: true,
    },
    {
        name: "Blog Architecture",
        slug: "blog-architecture",
        standalone: true,
    },
    {
        name: "Books",
        slug: "books",
        standalone: true,
    },
    {
        name: "Software Architecture",
        slug: "software-architecture",
        standalone: true,
    },
    {
        name: "General",
        slug: "general",
        pages: [
            { name: "API Design Guidelines", slug: "api-design-guidelines" },
            { name: "Computing", slug: "computing" },
            { name: "Database", slug: "database" },
            { name: "Kafka", slug: "kafka" },
            { name: "OAuth2 and OIDC", slug: "oauth2-and-oidc" },
        ],
    },
    {
        name: "Golang",
        slug: "golang",
        pages: [
            { name: "Compiler", slug: "compiler" },
            { name: "Goroutine", slug: "goroutine" },
            { name: "Strings", slug: "strings" },
        ],
    },
    {
        name: "Math",
        slug: "math",
        pages: [
            { name: "Calculus", slug: "calculus" },
            { name: "Linear Algebra", slug: "linear-algebra" },
            { name: "Sequence, Series, Limit", slug: "sequence-series-limit" },
            { name: "Summary", slug: "summary" },
            { name: "Trigonometry", slug: "trigonometry" },
            {
                name: "Precalculus",
                slug: "precalculus",
                isFolder: true,
                pages: [
                    { name: "Summary", slug: "summary" },
                ],
            },
        ],
    },
    {
        name: "ML",
        slug: "ml",
        pages: [
            { name: "Chunking and Embedding", slug: "chunking-and-embedding" },
        ],
    },
    {
        name: "System Design",
        slug: "system-design",
        pages: [
            { name: "Consistent Hashing", slug: "consistent-hashing" },
            { name: "Distributed Cache", slug: "distributed-cache" },
            { name: "Distributed Task Scheduler", slug: "distributed-task-scheduler" },
            { name: "ID Generator", slug: "id-generator" },
            { name: "Notification System", slug: "notification-system" },
            { name: "Rate Limit", slug: "rate-limit" },
        ],
    },
];
