// AUTO-GENERATED by scripts/gen-nav.js — do not edit by hand.
// Run `node scripts/gen-nav.js` (or `./build.sh`) to regenerate.
const navigationData = [
    {
        name: "Introduction",
        slug: "README",
        standalone: true,
    },
    {
        name: "ReactJS",
        slug: "reactjs",
        standalone: true,
    },
    {
        name: "etcd & Raft",
        slug: "etcd-raft",
        standalone: true,
    },
    {
        name: "ML",
        slug: "ml",
        standalone: true,
    },
    {
        name: "Psyhco",
        slug: "psyhco",
        standalone: true,
    },
    {
        name: "Rag",
        slug: "rag",
        standalone: true,
    },
    {
        name: "Saas Template",
        slug: "saas-template",
        standalone: true,
    },
    {
        name: "Syncthing",
        slug: "syncthing",
        standalone: true,
    },
    {
        name: "Fundamentals",
        slug: "fundamental",
        pages: [
            { name: "API Best Practices", slug: "api-design-guidelines" },
            { name: "Computing", slug: "computing" },
            { name: "Database", slug: "database" },
            { name: "Kafka", slug: "kafka" },
            { name: "Networking", slug: "networking" },
            { name: "OAuth2 and OIDC", slug: "oauth2-and-oidc" },
            { name: "Software Architecture", slug: "software-architecture" },
        ],
    },
    {
        name: "System Design",
        slug: "system-design",
        pages: [
            { name: "Cache Stampede Flash Sale", slug: "cache-stampede-flash-sale" },
            { name: "Consistent Hashing Distributed Cache", slug: "consistent-hashing-distributed-cache" },
            { name: "Distributed Cache Live Streaming Chat", slug: "distributed-cache-live-streaming-chat" },
            { name: "Distributed Task Scheduler Batch Job Processing", slug: "distributed-task-scheduler-batch-job-processing" },
            { name: "Event Processing Order Notifications", slug: "event-processing-order-notifications" },
            { name: "ID Generator", slug: "id-generator" },
            { name: "Order Notification System", slug: "order-notification-system" },
            { name: "RabbitMQ", slug: "rabbitmq" },
        ],
    },
    {
        name: "Golang",
        slug: "golang",
        pages: [
            { name: "Goroutine", slug: "goroutine" },
            { name: "Strings", slug: "strings" },
        ],
    },
    {
        name: "Math",
        slug: "math",
        pages: [
            { name: "Calculus", slug: "calculus" },
            { name: "Linear Algebra", slug: "linear-algebra" },
            { name: "Sequence, Series, Limit", slug: "sequence-series-limit" },
            { name: "Summary", slug: "summary" },
            { name: "Trigonometry", slug: "trigonometry" },
            {
                name: "Precalculus",
                slug: "precalculus",
                isFolder: true,
                pages: [
                    { name: "Summary", slug: "summary" },
                ],
            },
        ],
    },
];
