// AUTO-GENERATED by scripts/gen-nav.js — do not edit by hand.
// Run `node scripts/gen-nav.js` (or `./build.sh`) to regenerate.
const navigationData = [
    {
        name: "Introduction",
        slug: "README",
        standalone: true,
    },
    {
        name: "RAG",
        slug: "e2e-production-rag",
        standalone: true,
    },
    {
        name: "ML",
        slug: "ml",
        standalone: true,
    },
    {
        name: "Quant",
        slug: "quant",
        standalone: true,
    },
    {
        name: "Fundamentals",
        slug: "fundamental",
        pages: [
            { name: "API Best Practices", slug: "api-design-guidelines" },
            { name: "Computing", slug: "computing" },
            { name: "Database", slug: "database" },
            { name: "Domain", slug: "domain" },
            { name: "Kafka", slug: "kafka" },
            { name: "Networking", slug: "networking" },
            { name: "OAuth2 and OIDC", slug: "oauth2-and-oidc" },
            { name: "Rabbitmq", slug: "rabbitmq" },
            { name: "Reactjs", slug: "reactjs" },
            { name: "Software Architecture", slug: "software-architecture" },
        ],
    },
    {
        name: "System Design",
        slug: "system-design",
        pages: [
            { name: "Cache Stampede", slug: "cache-stampede" },
            { name: "Consistent Hashing", slug: "consistent-hashing" },
            { name: "Distributed Cache", slug: "distributed-cache" },
            { name: "Distributed Task Scheduler", slug: "distributed-task-scheduler" },
            { name: "Event Processing", slug: "event-processing" },
            { name: "ID Generator", slug: "id-generator" },
            { name: "Notification System", slug: "notification-system" },
            { name: "Rate Limit", slug: "rate-limit" },
        ],
    },
    {
        name: "Golang",
        slug: "golang",
        pages: [
            { name: "Goroutine", slug: "goroutine" },
            { name: "Strings", slug: "strings" },
        ],
    },
    {
        name: "Math",
        slug: "math",
        pages: [
            { name: "Calculus", slug: "calculus" },
            { name: "Linear Algebra", slug: "linear-algebra" },
            { name: "Sequence, Series, Limit", slug: "sequence-series-limit" },
            { name: "Summary", slug: "summary" },
            { name: "Trigonometry", slug: "trigonometry" },
            {
                name: "Precalculus",
                slug: "precalculus",
                isFolder: true,
                pages: [
                    { name: "Summary", slug: "summary" },
                ],
            },
        ],
    },
];
