// Search configuration constants
const SEARCH_CONFIG = {
    MAX_QUERY_LENGTH: 100,
    MAX_RESULTS: 10,
    SNIPPET_LENGTH: 100,
    SNIPPET_CONTEXT_BEFORE: 40,
    SNIPPET_CONTEXT_AFTER: 60,
    DEBOUNCE_MS: 300
};

class Search {
    constructor() {
        // navigationData no longer needed at runtime — index is pre-built at build time
        this.searchIndex = [];
        this.searchQuery = '';
        this.searchResults = [];
    }

    // Fetch the pre-built index (1 request vs N markdown fetches).
    // Generated by scripts/gen-search-index.js during `./build.sh`.
    async init() {
        try {
            const res = await fetch('/search-index.json');
            if (res.ok) {
                this.searchIndex = await res.json();
            } else {
                console.warn('search-index.json not found — run ./build.sh to generate it');
            }
        } catch (e) {
            console.warn('Failed to load search index', e);
        }
    }

    performSearch(query) {
        this.searchQuery = query;

        if (this.searchQuery.length < 2) {
            this.searchResults = [];
            return [];
        }

        if (this.searchQuery.length > SEARCH_CONFIG.MAX_QUERY_LENGTH) {
            this.searchResults = [];
            return [];
        }

        const lowerQuery = this.searchQuery.toLowerCase();
        const results = this.searchIndex.filter(item => {
            return item.title.toLowerCase().includes(lowerQuery) ||
                item.plainText.toLowerCase().includes(lowerQuery);
        });

        this.searchResults = results.map(item => {
            const snippet = this.getSnippet(item.plainText, lowerQuery);
            return { ...item, snippet };
        }).slice(0, SEARCH_CONFIG.MAX_RESULTS);

        return this.searchResults;
    }

    getSnippet(text, query) {
        const index = text.toLowerCase().indexOf(query);
        if (index === -1) return text.slice(0, SEARCH_CONFIG.SNIPPET_LENGTH) + '...';

        const start = Math.max(0, index - SEARCH_CONFIG.SNIPPET_CONTEXT_BEFORE);
        const end = Math.min(text.length, index + query.length + SEARCH_CONFIG.SNIPPET_CONTEXT_AFTER);

        return (start > 0 ? '...' : '') +
            text.slice(start, end) +
            (end < text.length ? '...' : '');
    }

    highlightText(text, query) {
        if (!query) return text;
        const regex = new RegExp(
            `(${query.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')})`,
            'gi'
        );
        return text.replace(regex, '<span class="search-highlight">$1</span>');
    }

    clear() {
        this.searchQuery = '';
        this.searchResults = [];
    }

    getResults() {
        return this.searchResults;
    }

    getQuery() {
        return this.searchQuery;
    }
}