#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const { ROOT, SRC } = require('./lib/paths');
const { IGNORE, NAME_OVERRIDES, ROOT_PAGE_ORDER, CATEGORY_ORDER } = require('./lib/config');

const OUTPUT_JS = path.join(SRC, 'js/navigation-data.js');
const OUTPUT_JSON = path.join(SRC, 'js/navigation-data.json');

function toName(slug) {
    if (NAME_OVERRIDES[slug]) return NAME_OVERRIDES[slug];
    return slug
        .split('-')
        .map(w => w.charAt(0).toUpperCase() + w.slice(1))
        .join(' ');
}

function slugFromFile(filename) {
    return filename.replace(/\.md$/, '');
}

function scanDir(dirPath, depth = 0) {
    const entries = fs.readdirSync(dirPath, { withFileTypes: true });
    const pages = [];

    const files = entries
        .filter(e => e.isFile() && e.name.endsWith('.md') && e.name !== 'README.md' && !IGNORE.has(e.name))
        .map(e => slugFromFile(e.name))
        .sort();

    const dirs = entries
        .filter(e => e.isDirectory() && !IGNORE.has(e.name))
        .map(e => e.name)
        .sort();

    for (const slug of files) {
        pages.push({ name: toName(slug), slug });
    }

    for (const slug of dirs) {
        const subPath = path.join(dirPath, slug);
        const hasReadme = fs.existsSync(path.join(subPath, 'README.md'));
        if (!hasReadme) continue;

        if (depth === 0) {
            const subPages = scanDir(subPath, depth + 1);
            const entry = { name: toName(slug), slug, isFolder: true };
            if (subPages.length > 0) entry.pages = subPages;
            pages.push(entry);
        }
    }

    return pages;
}

function buildNav() {
    const nav = [];

    const rootMdFiles = fs.readdirSync(ROOT, { withFileTypes: true })
        .filter(e => e.isFile() && e.name.endsWith('.md') && !IGNORE.has(e.name))
        .map(e => slugFromFile(e.name));

    const orderedRootPages = [
        ...ROOT_PAGE_ORDER.filter(s => rootMdFiles.includes(s)),
        ...rootMdFiles.filter(s => !ROOT_PAGE_ORDER.includes(s)).sort(),
    ];

    for (const slug of orderedRootPages) {
        nav.push({ name: toName(slug), slug, standalone: true });
    }

    const rootDirs = fs.readdirSync(ROOT, { withFileTypes: true })
        .filter(e => e.isDirectory() && !IGNORE.has(e.name) && !e.name.startsWith('.'))
        .map(e => e.name);

    const orderedCategories = [
        ...CATEGORY_ORDER.filter(s => rootDirs.includes(s)),
        ...rootDirs.filter(s => !CATEGORY_ORDER.includes(s)).sort(),
    ];

    for (const slug of orderedCategories) {
        const dirPath = path.join(ROOT, slug);
        const pages = scanDir(dirPath);
        const entry = { name: toName(slug), slug };
        if (pages.length > 0) entry.pages = pages;
        nav.push(entry);
    }

    return nav;
}

function serialize(nav) {
    const lines = [];
    lines.push('// AUTO-GENERATED by scripts/gen-nav.js — do not edit by hand.');
    lines.push('// Run `node scripts/gen-nav.js` (or `./build.sh`) to regenerate.');
    lines.push('const navigationData = [');

    for (const item of nav) {
        lines.push('    {');
        lines.push(`        name: ${JSON.stringify(item.name)},`);
        lines.push(`        slug: ${JSON.stringify(item.slug)},`);
        if (item.standalone) lines.push(`        standalone: true,`);
        if (item.isFolder)   lines.push(`        isFolder: true,`);
        if (item.pages) {
            lines.push(`        pages: [`);
            for (const page of item.pages) {
                serializePage(lines, page, 3);
            }
            lines.push(`        ],`);
        }
        lines.push('    },');
    }

    lines.push('];');
    lines.push('');
    return lines.join('\n');
}

function serializePage(lines, page, indent) {
    const pad = '    '.repeat(indent);
    if (page.pages) {
        lines.push(`${pad}{`);
        lines.push(`${pad}    name: ${JSON.stringify(page.name)},`);
        lines.push(`${pad}    slug: ${JSON.stringify(page.slug)},`);
        if (page.isFolder) lines.push(`${pad}    isFolder: true,`);
        lines.push(`${pad}    pages: [`);
        for (const sub of page.pages) {
            serializePage(lines, sub, indent + 2);
        }
        lines.push(`${pad}    ],`);
        lines.push(`${pad}},`);
    } else {
        const isFolder = page.isFolder ? `, isFolder: true` : '';
        lines.push(`${pad}{ name: ${JSON.stringify(page.name)}, slug: ${JSON.stringify(page.slug)}${isFolder} },`);
    }
}

const nav = buildNav();
const output = serialize(nav);
fs.writeFileSync(OUTPUT_JS, output, 'utf8');
fs.writeFileSync(OUTPUT_JSON, JSON.stringify(nav, null, 2), 'utf8');
console.log(`navigation-data.js written (${nav.length} top-level entries)`);
